---
title: "Ch15_lab"
author: "Holden Jones"
date: '2022-10-27'
output: html_document
---

# Factors


--------------------------------------------------------------------------------
# 15.1 Introduction

factors used to work with categorical variables, factors easier to work with so
base R automatically converts categorical variables to factors, but not in tidy

## 15.1.1 Prerequisites

use the forcats package
```{r}
library(tidyverse)
```

## 15.1.2 Learning more

Read Amelia McNamara and Nicholas Horton's paper; Wrangling categorical data in R


--------------------------------------------------------------------------------
# 15.2 Creating factors

Imagine that you have a variable that records month:
```{r}
x1 <- c("Dec", "Apr", "Jan", "Mar")

# Using a string to record this variable has two problems:
# only 12 months, and can make typos
x2 <- c("Dec", "Apr", "Jam", "Mar")

# and doesn't sort in good way:
sort(x1)
```

You can fix both of these problems with a factor. To create a factor you must 
start by creating a list of the valid levels:
```{r}
month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", 
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
)

# now can create a factor:
y1 <- factor(x1, levels = month_levels)
y1
sort(y1)

# any values not in levels set will silently become NA:
y2 <- factor(x2, levels = month_levels)
y2

# if we omit levels, will be taken from data in alphabetical order:
factor(x1)

# sometimes prefer that order of levels matches order of first appearence:
# use unique() or after the fact with fct_inorder():
f1 <- factor(x1, levels = unique(x1))
f1

f2 <- x1 %>% factor() %>% fct_inorder()
f2

# if need to access levels, can do so with levels():
levels(f2)
```


--------------------------------------------------------------------------------
# 15.3 General Social Survey

focusing rest of chapter on data from GSS, U of Chicago survey
```{r}
gss_cat

# quick view of different variables with count:
gss_cat %>%
  count(race)

gss_cat  %>%
  count(relig)

# or bar chart:
ggplot(gss_cat, aes(race)) +
  geom_bar()

ggplot(gss_cat, aes(relig)) +
  geom_bar()

# by default ggplot will drop levels without any values, can force them to show:
ggplot(gss_cat, aes(race)) +
  geom_bar() +
  scale_x_discrete(drop = FALSE)
```

## 15.3.1 Exercises

1. Explore the distribution of rincome (reported income). What makes the default 
  bar chart hard to understand? How could you improve the plot?
```{r}
# default includes lots of things like don't know, NA, and the ordering is off
gss_cat %>%
  ggplot(aes(rincome)) +
   geom_bar()

# can remove non numerical cases
gss_cat %>%
  filter(!rincome == 'Not applicable',
         !rincome == 'No answer',
         !rincome == "Don't know",
         !rincome == 'Refused') %>%
  ggplot(aes(rincome)) +
   geom_bar() +
   scale_x_discrete(limits = rev(levels(gss_cat$rincome)), drop = TRUE)

# also can reorder x axes to be in descending order
gss_cat %>%
  ggplot(aes(rincome)) +
   geom_bar() +
   scale_x_discrete(limits = rev(levels(gss_cat$rincome)), drop = FALSE)
```

2. What is the most common relig in this survey? What’s the most common partyid?
```{r}
# Protestant most common relig
gss_cat %>%
  count(relig) %>%
  arrange(desc(n)) %>%
  head(1)

# Independent most common partyid
gss_cat %>%
  count(partyid) %>%
  arrange(desc(n)) %>%
  head(1)
```

3. Which relig does denom (denomination) apply to? How can you find out with a 
  table? How can you find out with a visualisation?
*answer sheet*
```{r}
# filter out no answer responses to denomination, all remaining are Protestant
gss_cat %>%
  filter(!denom %in% c(
    "No answer", "Other", "Don't know", "Not applicable",
    "No denomination"
  )) %>%
  count(relig)

# also clear in scatterplot
gss_cat %>%
  count(relig, denom) %>%
  ggplot(aes(x = relig, y = denom, size = n)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90))
```


--------------------------------------------------------------------------------
# 15.4 Modifying factor order




