---
title: "Ch22_lab"
author: "Holden Jones"
date: '2023-01-24'
output: html_document
---

# Modeling - Introduction

focus of this book is on exploration - using tools learned previously

goal of a model:
- provide simple low-dimensional summary of dataset
- capture true "signals" - patterns generated by phenomenon of interest
- ignore "noise" -random variation not interested in

here only focus on "predictive" models - generate predictions!
- another type is "data discovery"

not going to be a deep dive
- model basiccs - how models work mechanistically, focus on linear models
- model building - how to use modes to pull out patterns
- many models - how to use many simple models to understand complex datasets

--------------------------------------------------------------------------------

# 22.1 Hypothesis generation vs. hypothesis confirmation

here going to use models for exploration - not how normally taught

traditional focus on models is inference - confirming that hypothesis is true
- doing this correctly is not complicated, but it is hard (what)
- 2 key ideas to understand to do inference correctly:
  - each obs. can either be used for exploration or confirmation, but not both
  - can use an obs. as many times as like for exploration, but only once for 
    confirmation. as soon as use an observation twice, switched from confirmation
    to exploration
    
to confirm a hypothesis must use data independent of the data used to generate!

if want to confirmatory analysis, one approach to split data into 3 pieces before
beginning:
- 60% of data goes into training (exploration) set - allowed to do anything to this
- 20% goes into query set - use this to compare models or visualizations by hand
  cannot be used as part of automated process
- 20% reserved for test set. can only use this data ONCE to test final model

partitioning allows you to explore training data, occassionally generate 
  candidate hypotheseses that check with query set. wehn confident have right 
  model, can check it once with test data
  









